### ISSUE TITLE
Brightness stops syncing if you bring the internal display brightness all the way to zero

### ISSUE THREAD

**Issue by alexspeller** [OCJvanDijk/Brightness-Sync#1] opened 2019-06-21 12:03 UTC
If you turn the internal display brightness all the way down, then the brightness stops syncing until you relaunch the app.

Otherwise it's working really well for me, thanks for the great app that really should be provided by LG!

**Comment by OCJvanDijk** [comment] 2019-07-02 20:51
@alexspeller Hey, thanks for filling an issue. Apparently I don't have email notifications properly set up otherwise I would have seen it earlier. I can reproduce it easily, I'm off to investigate!

**Comment by OCJvanDijk** [comment] 2019-07-02 21:52
Seems like I already fixed this more than 3 weeks ago in commit ec05d08, but I didn't release it because I didn't actually realize I fixed anything 🤷‍♂️. Fix now released in 1.0.4.

**Closed by OCJvanDijk** 2019-07-02 21:52 UTC
