### ISSUE TITLE
v2.3.2 reads "Deactivated" all the time

### ISSUE THREAD

**Issue by blinkengus** [OCJvanDijk/Brightness-Sync#33] opened 2021-02-22 19:11 UTC
on macOS 11.2.1 / 2020 i7 Air with 27UN880-B, no matter what I do, and even after a restart the status in the Brightness-Sync drop down menu reads "Deactivated"
![image](https://user-images.githubusercontent.com/292948/108757374-9c6f7f00-74fe-11eb-9407-2821f738ee07.png)

**Comment by OCJvanDijk** [comment] 2021-02-22 19:24
Duplicate of #31

This app only works with LG 22MD4KA, 24MD4KL, 27MD5KA and 27MD5KL

When I released this app I was only aware of these type of monitors carrying the UltraFine brand. There’s been a lot of confusion and I’ve been meaning to clear this up. I’ll update the home page tomorrow.

Sorry for the confusion.

**Closed by OCJvanDijk** 2021-02-22 19:24 UTC

**Comment by blinkengus** [comment] 2021-02-22 19:38
Oh no worries -- that makes sense! Thanks just the same!
